import 'package:esm/resources/utils/Constants.dart';

class PendingRequestModel {
  String id;
  String myEventTitle;
  String myEventDate;
  String myEventStartTime;
  String myEventEndTime;
  String myEventImage;
  String eventOwnerName;
  String eventNature;
  String eventTimeZone;
  String eventPrice;
  String eventNote;
  String eventType;
  String eventLocation;
  String eventDressCode;
  //
  String eventLocalPrice;
  String receiveGift;
  String hologramTitle;
  String country;
  String bankType;
  String accountNumber;
  String bankName;
  String bankHolderName;
  String routingNumber;
  String engineerName;
  String engineerContactNumber;
  String workerType;
  String workerName;
  String workerContactNumber;
  bool eventPriceStatus;

  PendingRequestModel({
    required this.id,
    required this.myEventTitle,
    required this.myEventDate,
    required this.myEventStartTime,
    required this.myEventEndTime,
    required this.myEventImage,
    required this.eventOwnerName,
    required this.eventNature,
    required this.eventTimeZone,
    required this.eventPrice,
    required this.eventNote,
    required this.eventType,
    required this.eventLocation,
    required this.eventDressCode,
    required this.eventPriceStatus,
    required this.eventLocalPrice,
    required this.receiveGift,
    required this.hologramTitle,
    required this.country,
    required this.bankType,
    required this.accountNumber,
    required this.bankName,
    required this.bankHolderName,
    required this.routingNumber,
    required this.engineerName,
    required this.engineerContactNumber,
    required this.workerType,
    required this.workerName,
    required this.workerContactNumber,
  });

  factory PendingRequestModel.fromJson(Map<String, dynamic> json) {
    return PendingRequestModel(
      id: json['id'].toString(),
      myEventTitle: json['myEventTitle'],
      myEventDate: json['myEventDate'],
      myEventStartTime: json['myEventStartTime'],
      myEventEndTime: json['myEventEndTime'],
      myEventImage: json['myEventImage'],
      eventOwnerName: json['eventOwnerName'],
      eventNature: json['eventNature'],
      eventTimeZone: json['eventTimeZone'],
      eventPrice: json['eventPrice'],
      eventNote: json['eventNote'],
      eventType: json['eventType'],
      eventLocation: json['eventLocation'],
      eventDressCode: json['eventDressCode'],
      eventPriceStatus: json['eventPriceStatus'],
      eventLocalPrice: json['eventLocalPrice'],
      receiveGift: json['receiveGift'],
      hologramTitle: json['hologramTitle'],
      country: json['country'],
      bankType: json['bankType'],
      accountNumber: json['accountNumber'],
      bankName: json['bankName'],
      bankHolderName: json['bankHolderName'],
      routingNumber: json['routingNumber'],
      engineerName: json['engineerName'],
      engineerContactNumber: json['engineerContactNumber'],
      workerType: json['workerType'],
      workerName: json['workerName'],
      workerContactNumber: json['workerContactNumber'],
    );
  }

  static List<PendingRequestModel> pendingRequestList = [
    PendingRequestModel(
      id: '1',
      myEventTitle: 'My Birtday',
      myEventDate: '16-12-2023',
      myEventStartTime: '04:00 pm',
      myEventEndTime: '06:00 pm',
      myEventImage: Constants.eventPic,
      eventOwnerName: 'Fisayo Olamigoke',
      eventNature: 'Business/Corporate Events',
      eventTimeZone: 'America/Chicago',
      eventPrice: '25 USD',
      eventNote: 'Come All',
      eventType: 'Workshops',
      eventLocation: '3432 Benfield Dr, Houston, TX 77082, USA',
      eventDressCode: 'All Type',
      eventPriceStatus: false,
      eventLocalPrice: 'Free Event',
      receiveGift: 'Yes',
      hologramTitle: 'Hologram Fan Rental-Preferred',
      country: 'United States',
      bankType: 'Bank_account',
      accountNumber: '0101616348',
      bankName: 'ABD Bank',
      bankHolderName: 'Fisayo Olamigoke',
      routingNumber: '9787897877878',
      engineerName: 'Monique Cole',
      engineerContactNumber: '+18325800666',
      workerType: 'Assist Calling Of Guests',
      workerName: 'Frank Williams',
      workerContactNumber: '+18325800666',
    ),
    PendingRequestModel(
      id: '1',
      myEventTitle: 'My Birtday',
      myEventDate: '16-12-2023',
      myEventStartTime: '04:00 pm',
      myEventEndTime: '06:00 pm',
      myEventImage: Constants.birthDayImage,
      eventOwnerName: 'Fisayo Olamigoke',
      eventNature: 'Business/Corporate Events',
      eventTimeZone: 'America/Chicago',
      eventPrice: '25 USD',
      eventNote: 'Come All',
      eventType: 'Workshops',
      eventLocation: '3432 Benfield Dr, Houston, TX 77082, USA',
      eventDressCode: 'All Type',
      eventPriceStatus: false,
      eventLocalPrice: 'Free Event',
      receiveGift: 'Yes',
      hologramTitle: 'Hologram Fan Rental-Preferred',
      country: 'United States',
      bankType: 'Bank_account',
      accountNumber: '0101616348',
      bankName: 'ABD Bank',
      bankHolderName: 'Fisayo Olamigoke',
      routingNumber: '9787897877878',
      engineerName: 'Monique Cole',
      engineerContactNumber: '+18325800666',
      workerType: 'Assist Calling Of Guests',
      workerName: 'Frank Williams',
      workerContactNumber: '+18325800666',
    ),
    PendingRequestModel(
      id: '1',
      myEventTitle: 'My Birtday',
      myEventDate: '16-12-2023',
      myEventStartTime: '04:00 pm',
      myEventEndTime: '06:00 pm',
      myEventImage: Constants.birthDayImage,
      eventOwnerName: 'Fisayo Olamigoke',
      eventNature: 'Business/Corporate Events',
      eventTimeZone: 'America/Chicago',
      eventPrice: '25 USD',
      eventNote: 'Come All',
      eventType: 'Workshops',
      eventLocation: '3432 Benfield Dr, Houston, TX 77082, USA',
      eventDressCode: 'All Type',
      eventPriceStatus: true,
      eventLocalPrice: 'Free Event',
      receiveGift: 'Yes',
      hologramTitle: 'Hologram Fan Rental-Preferred',
      country: 'United States',
      bankType: 'Bank_account',
      accountNumber: '0101616348',
      bankName: 'ABD Bank',
      bankHolderName: 'Fisayo Olamigoke',
      routingNumber: '9787897877878',
      engineerName: 'Monique Cole',
      engineerContactNumber: '+18325800666',
      workerType: 'Assist Calling Of Guests',
      workerName: 'Frank Williams',
      workerContactNumber: '+18325800666',
    ),
    PendingRequestModel(
      id: '1',
      myEventTitle: 'My Birtday',
      myEventDate: '16-12-2023',
      myEventStartTime: '04:00 pm',
      myEventEndTime: '06:00 pm',
      myEventImage: Constants.eventPic,
      eventOwnerName: 'Fisayo Olamigoke',
      eventNature: 'Business/Corporate Events',
      eventTimeZone: 'America/Chicago',
      eventPrice: '25 USD',
      eventNote: 'Come All',
      eventType: 'Workshops',
      eventLocation: '3432 Benfield Dr, Houston, TX 77082, USA',
      eventDressCode: 'All Type',
      eventPriceStatus: true,
      eventLocalPrice: 'Free Event',
      receiveGift: 'Yes',
      hologramTitle: 'Hologram Fan Rental-Preferred',
      country: 'United States',
      bankType: 'Bank_account',
      accountNumber: '0101616348',
      bankName: 'ABD Bank',
      bankHolderName: 'Fisayo Olamigoke',
      routingNumber: '9787897877878',
      engineerName: 'Monique Cole',
      engineerContactNumber: '+18325800666',
      workerType: 'Assist Calling Of Guests',
      workerName: 'Frank Williams',
      workerContactNumber: '+18325800666',
    ),
    PendingRequestModel(
      id: '1',
      myEventTitle: 'My Birtday',
      myEventDate: '16-12-2023',
      myEventStartTime: '04:00 pm',
      myEventEndTime: '06:00 pm',
      myEventImage: Constants.eventPic,
      eventOwnerName: 'Fisayo Olamigoke',
      eventNature: 'Business/Corporate Events',
      eventTimeZone: 'America/Chicago',
      eventPrice: '25 USD',
      eventNote: 'Come All',
      eventType: 'Workshops',
      eventLocation: '3432 Benfield Dr, Houston, TX 77082, USA',
      eventDressCode: 'All Type',
      eventPriceStatus: false,
      eventLocalPrice: 'Free Event',
      receiveGift: 'Yes',
      hologramTitle: 'Hologram Fan Rental-Preferred',
      country: 'United States',
      bankType: 'Bank_account',
      accountNumber: '0101616348',
      bankName: 'ABD Bank',
      bankHolderName: 'Fisayo Olamigoke',
      routingNumber: '9787897877878',
      engineerName: 'Monique Cole',
      engineerContactNumber: '+18325800666',
      workerType: 'Assist Calling Of Guests',
      workerName: 'Frank Williams',
      workerContactNumber: '+18325800666',
    ),
    PendingRequestModel(
      id: '1',
      myEventTitle: 'My Birtday',
      myEventDate: '16-12-2023',
      myEventStartTime: '04:00 pm',
      myEventEndTime: '06:00 pm',
      myEventImage: Constants.birthDayImage,
      eventOwnerName: 'Fisayo Olamigoke',
      eventNature: 'Business/Corporate Events',
      eventTimeZone: 'America/Chicago',
      eventPrice: '25 USD',
      eventNote: 'Come All',
      eventType: 'Workshops',
      eventLocation: '3432 Benfield Dr, Houston, TX 77082, USA',
      eventDressCode: 'All Type',
      eventPriceStatus: false,
      eventLocalPrice: 'Free Event',
      receiveGift: 'Yes',
      hologramTitle: 'Hologram Fan Rental-Preferred',
      country: 'United States',
      bankType: 'Bank_account',
      accountNumber: '0101616348',
      bankName: 'ABD Bank',
      bankHolderName: 'Fisayo Olamigoke',
      routingNumber: '9787897877878',
      engineerName: 'Monique Cole',
      engineerContactNumber: '+18325800666',
      workerType: 'Assist Calling Of Guests',
      workerName: 'Frank Williams',
      workerContactNumber: '+18325800666',
    ),
  ];
}
